// packages/react/src/components/AudioPlayer/components/Volume.tsx
import { memo } from 'react'
import { Slider, Popover, Button } from 'antd'
import { VolumeIcon, MuteIcon } from '../../../icons'

interface Props {
    volume: number
    isMute: boolean
    updateVolume: (val: number) => void
    onClick: () => void
}

const Volume = ({ volume, isMute, updateVolume, onClick }: Props) => {
    return (
        <Popover
            content={
                <Slider
                    value={volume}
                    tooltip={{ formatter: null }}
                    vertical
                    onChange={updateVolume}
                    style={{ height: 80 }}
                />
            }
            placement="top"
            overlayClassName="volume-control"
            overlayInnerStyle={{ padding: '10px 2px 6px 2px' }}
            overlayStyle={{ padding: 2 }}
        >
            <Button
                shape="circle"
                size="large"
                type="link"
                style={{ border: 'none' }}
                icon={
                    isMute ? (
                        <MuteIcon aria-label="muteIcon" />
                    ) : (
                        <VolumeIcon aria-label="volumeIcon" />
                    )
                }
                onClick={onClick}
                aria-label="volumeButton"
            />
        </Popover>
    )
}

export default memo(Volume)

// packages/vue/src/components/AudioPlayer/components/Volume.vue
<template>
    <a-popover placement="top" overlay-class-name="volume-control">
        <template #content>
            <a-slider
                :value="volume"
                :tooltip-visible="false"
                vertical
                @change="(val)=>{emit('update', val as number)}"
                class="volume-slider"
            />
        </template>
        <a-button
            shape="circle"
            size="large"
            type="link"
            :style="{ border: 'none', color: 'black' }"
            @click="
                () => {
                    emit('click')
                }
            "
            aria-label="volumeButton"
        >
            <template #icon>
                <mute-icon v-if="isMute" aria-label="muteIcon" />
                <volume-icon v-else aria-label="volumeIcon" />
            </template>
        </a-button>
    </a-popover>
</template>
<script setup lang="ts">
import { VolumeIcon, MuteIcon } from '@cardigan/icons'

interface VolumeProps {
    volume: number
    isMute: boolean
}

interface VolumeEmits {
    (e: 'click'): void
    (e: 'update', val: number): void
}

defineProps<VolumeProps>()
const emit = defineEmits<VolumeEmits>()
</script>
<style>
.volume-control .ant-popover-inner-content {
    padding: 10px 2px 6px 2px;
}
</style>
<style scoped>
.volume-slider {
    height: 80px;
}
</style>
