// demo/vue/example/Overview.vue
<template>
    <a-list :grid="{ gutter: 16, column: 3 }" :data-source="componentsList">
        <template #renderItem="{ item: { name, label } }">
            <a-list-item>
                <router-link :to="`/components/${name}`">
                    <a-card
                        :title="`${name} ${label}`"
                        :bodyStyle="{ textAlign: 'center' }"
                        hoverable
                    >
                        <a-image
                            :height="160"
                            :src="`../assets/${name}.png`"
                            :preview="false"
                        />
                    </a-card>
                </router-link>
            </a-list-item>
        </template>
    </a-list>
</template>
<script setup lang="ts">
import componentsList from '../componentsList'
</script>

// demo/react/examples/Overview.tsx
import { Card, List, Image } from 'antd'
import { Link } from 'react-router-dom'
import componentsList from '../componentsList'

const Overview = () => (
    <List
        grid={{ gutter: 16, column: 3 }}
        dataSource={componentsList}
        renderItem={({ name, label }) => (
            <List.Item>
                <Link to={`/components/${name}`}>
                    <Card title={`${name} ${label}`} hoverable>
                        <Image src={`../assets/${name}.png`} preview={false} />
                    </Card>
                </Link>
            </List.Item>
        )}
    />
)

export default Overview
