// docs/react/demo/AudioPlayer/file.tsx
import { useState } from 'react'
import { Upload, Button, Space } from 'antd'
import { AudioPlayer } from '@corgi/react'

const AudioPlayerDemo = () => {
    const [file, setFile] = useState<null | File>(null)

    const beforeUpload = (val: File) => {
        setFile(val)
    }

    return (
        <Space direction="vertical">
            <Upload beforeUpload={beforeUpload} showUploadList={false}>
                <Button>选择文件</Button>
            </Upload>
            <AudioPlayer source={file} />
        </Space>
    )
}

export default AudioPlayerDemo

// demo/vue/example/AudioPlayer/File.vue
<template>
    <a-space direction="vertical">
        <a-upload
            :before-upload="beforeUpload"
            :custom-request="() => {}"
            :show-upload-list="false"
        >
            <a-button>选择文件</a-button>
        </a-upload>
        <audio-player :source="file" show-volume-control />
    </a-space>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import { AudioPlayer } from '@corgwn/vue'

const file = ref<null | File>(null)

const beforeUpload = async (val: File) => {
    file.value = val
}
</script>
