// docs/react/demo/AudioPlayer/link.tsx
import { AudioPlayer } from '@corgii/react'

const AudioPlayerDemo = () => (
    <AudioPlayer
        source="https://howlerjs.com/assets/howler.js/examples/player/audio/rave_digger.webm"
        cover="https://github.com/JavanShen/corgi/blob/main/docs/react/public/corgi.png?raw=true"
        title="corgii"
        artist="apine"
    />
)

export default AudioPlayerDemo

// demo/vue/example/AudioPlayer/Link.vue
<template>
    <AudioPlayer
        source="https://howlerjs.com/assets/howler.js/examples/player/audio/rave_digger.webm"
        cover="https://github.com/JavanShen/corgi/blob/main/docs/react/public/corgi.png?raw=true"
        title="corgwn"
        artist="apine"
    />
</template>
<script setup lang="ts">
import { AudioPlayer } from '@corgwn/vue'
</script>
