// packages/vue/src/components/AudioPlayer/index.vue
<template>
    <a-card class="card">
        <div class="audio-container">
            <div class="audio-content">
                <div
                    class="title text-omission"
                    aria-label="title"
                    :title="title || id3Title"
                >
                    {{ title || id3Title }}
                </div>
                <div
                    class="sub-title text-omission"
                    aria-label="artist"
                    :title="artist || id3Artist"
                >
                    {{ artist || id3Artist }}
                </div>
                <a-slider
                    :value="currentTime"
                    :max="totalTime"
                    :tooltip-visible="false"
                    @change="(val)=>{updateTime(val as number)}"
                    @after-change="(val)=>{jump(val as number)}"
                    :disabled="!isCanPlay"
                    class="progress-bar"
                />
                <div class="flex-between">
                    <div
                        class="sub-sub-title text-omission"
                        aria-label="currentTimeText"
                    >
                        {{ currentTimeText }}
                    </div>
                    <div
                        class="sub-sub-title text-omission"
                        aria-label="totalTimeText"
                    >
                        {{ totalTimeText }}
                    </div>
                </div>
                <div class="flex-between">
                    <a-button
                        size="large"
                        type="text"
                        shape="circle"
                        :disabled="!isCanPlay"
                        :style="{ border: 'none' }"
                        :aria-label="isPlay ? 'pause' : 'play'"
                        @click="
                            () => {
                                return isPlay ? pause() : play()
                            }
                        "
                    >
                        <template #icon>
                            <pause-icon v-if="isPlay" />
                            <play-icon v-else />
                        </template>
                    </a-button>
                    <Volume
                        :volume="volume || 0"
                        :isMute="!volume"
                        @click="
                            () => {
                                return volume ? mute() : unmute()
                            }
                        "
                        @update="updateVolume"
                    />
                </div>
            </div>
            <div
                class="audio-media"
                aria-label="cover"
                v-if="(imageSrc || cover) && cover !== false"
            >
                <a-image
                    :preview="false"
                    :src="cover || imageSrc"
                    :height="175"
                    :width="175"
                ></a-image>
            </div>
        </div>
    </a-card>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { PlayIcon, PauseIcon } from '@cardigan/icons'
import { usePlayAudio } from '@corgwn/composables'
import type { AudioSource } from '@corgwn/types'
import Volume from './components/Volume.vue'

interface AudioPlayerProps {
    source: AudioSource | null
    cover?: false | string
    title?: string
    artist?: string
    showVolumeControl?: boolean
}

interface AudioPlayerEmits {
    (e: 'loaded'): void
}

const prop = withDefaults(defineProps<AudioPlayerProps>(), {
    source: '',
    showVolumeControl: false,
    cover: undefined,
    title: undefined,
    artist: undefined
})

const emit = defineEmits<AudioPlayerEmits>()

const {
    currentTime,
    currentTimeText,
    totalTime,
    totalTimeText,
    imageSrc,
    title: id3Title,
    artist: id3Artist,
    play,
    pause,
    updateTime,
    jump,
    isPlay,
    isCanPlay,
    volume,
    updateVolume,
    mute,
    unmute
} = usePlayAudio(
    computed(() => prop.source || ''),
    () => {
        emit('loaded')
    }
)
</script>

<style scoped>
.card {
    display: inline-flex;
    width: max-content;
}

.audio-container {
    display: flex;
    flex-flow: row nowrap;
}

.audio-content {
    display: flex;
    flex-flow: column nowrap;
    min-width: 170px;
    max-width: 200px;
    justify-content: space-between;
}

.text-omission {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.title {
    font-size: 22px;
    color: black;
    text-align: start;
}

.sub-title {
    font-size: 16px;
    color: #838383;
}

.sub-sub-title {
    font-size: 14px;
    color: #838383;
}

.flex-between {
    display: flex;
    justify-content: space-between;
}

.audio-media {
    margin-left: 10px;
    border-radius: 5px;
    overflow: hidden;
    height: 175px;
    width: 175px;
}
</style>

// packages/react/AudioPlayer/index.tsx
import { Card, Slider, Button, Image } from 'antd'
import { usePlayAudio } from '@corgi/hooks'
import styled from '@emotion/styled'

import type { Source } from '@corgi/types'
import { PlayIcon, PauseIcon } from '../icons'

interface Props {
    source: Source
    loaded?: () => void
}

const textOmission = {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap'
} as const

const AudioContent = styled.div({
    display: 'flex',
    flexFlow: 'column nowrap',
    minWidth: 170,
    maxWidth: 200,
    flex: 2,
    justifyContent: 'space-between'
})

const AudioContainer = styled.div({
    display: 'flex',
    flexFlow: 'row nowrap'
})

const AudioMedia = styled.div({
    marginLeft: 10,
    flex: 1,
    borderRadius: 5,
    overflow: 'hidden'
})

const Title = styled.div({
    fontSize: 22,
    color: 'black',
    ...textOmission
})

const SubTitle = styled.div({
    fontSize: 16,
    color: '#838383',
    ...textOmission
})

const SubTitle2 = styled.div({
    fontSize: 14,
    color: '#838383',
    ...textOmission
})

const FlexBetween = styled.div({
    display: 'flex',
    justifyContent: 'space-between'
})

const AudioPlayer = ({ source, loaded }: Props) => {
    const {
        currentTime,
        currentTimeText,
        totalTime,
        totalTimeText,
        imageSrc,
        title,
        artist,
        play,
        pause,
        updateTime,
        jump,
        isPlay
    } = usePlayAudio(source, loaded)

    return (
        <Card
            style={{
                display: 'inline-flex',
                width: 'max-content'
            }}
        >
            <AudioContainer>
                <AudioContent>
                    <Title aria-label="title">{title}</Title>
                    <SubTitle aria-label="artist">{artist}</SubTitle>
                    <Slider
                        value={currentTime}
                        max={totalTime}
                        tooltip={{ formatter: null }}
                        onChange={updateTime}
                        onAfterChange={jump}
                    />
                    <FlexBetween>
                        <SubTitle2 aria-label="currentTimeText">
                            {currentTimeText}
                        </SubTitle2>
                        <SubTitle2 aria-label="totalTimeText">
                            {totalTimeText}
                        </SubTitle2>
                    </FlexBetween>
                    <Button
                        size="large"
                        type="text"
                        shape="circle"
                        aria-label={isPlay ? 'pause' : 'play'}
                        icon={isPlay ? <PauseIcon /> : <PlayIcon />}
                        onClick={() => {
                            return isPlay ? pause() : play()
                        }}
                    />
                </AudioContent>
                {imageSrc ? (
                    <AudioMedia>
                        <Image preview={false} src={imageSrc} width={175} />
                    </AudioMedia>
                ) : null}
            </AudioContainer>
        </Card>
    )
}

export default AudioPlayer
